//! The preset tables, split by tier.
//!
//! A `base_url` is everything **before** the request path: the provider layer
//! appends `/chat/completions` for `openai-compatible` connections and
//! `/messages` for `anthropic-native` ones
//! (`alnair_llm::providers::common::normalize_base_url` only trims a trailing
//! slash). Endpoints were cross-checked against 9Router's provider registry and,
//! where one exists, the vendor's own documentation.

use super::{ProviderPreset, api_key, free_tier, local};

/// Paid and pay-as-you-go endpoints behind an API key.
pub(super) fn api_key_presets() -> Vec<ProviderPreset> {
    vec![
        api_key(
            "alibaba",
            "Alibaba",
            "openai-compatible",
            "https://coding.dashscope.aliyuncs.com/v1",
            "https://bailian.console.aliyun.com/?apiKey=1",
            Some("Aliyun Coding Plan endpoint (China)."),
        ),
        api_key(
            "alibaba-coding",
            "Alibaba Coding",
            "openai-compatible",
            "https://coding-intl.dashscope.aliyuncs.com/v1",
            "https://modelstudio.console.alibabacloud.com/?apiKey=1",
            Some("International Coding Plan endpoint."),
        ),
        api_key(
            "alibaba-studio",
            "Alibaba Studio",
            "openai-compatible",
            "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
            "https://modelstudio.console.alibabacloud.com/?apiKey=1",
            Some("DashScope's OpenAI-compatible mode; rejects Coding Plan keys."),
        ),
        api_key(
            "alibaba-token-plan",
            "Alibaba Token Plan",
            "openai-compatible",
            "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
            "https://modelstudio.console.alibabacloud.com/?apiKey=1",
            Some("Token-plan endpoint, Singapore region only."),
        ),
        api_key(
            "anthropic",
            "Anthropic",
            "anthropic-native",
            "https://api.anthropic.com/v1",
            "https://console.anthropic.com/settings/keys",
            None,
        ),
        api_key(
            "azure-openai",
            "Azure OpenAI",
            "openai-compatible",
            "https://<your-resource>.openai.azure.com/openai/v1",
            "https://portal.azure.com/#view/Microsoft_Azure_ProjectOxford/CognitiveServicesHub/~/OpenAI",
            Some("Replace <your-resource>; the deployment name is the model id."),
        ),
        api_key(
            "qianfan",
            "Baidu Qianfan",
            "openai-compatible",
            "https://qianfan.baidubce.com/v2",
            "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
            None,
        ),
        api_key(
            "blackbox",
            "Blackbox AI",
            "openai-compatible",
            "https://api.blackbox.ai/v1",
            "https://www.blackbox.ai/api-management",
            None,
        ),
        api_key(
            "cerebras",
            "Cerebras",
            "openai-compatible",
            "https://api.cerebras.ai/v1",
            "https://cloud.cerebras.ai",
            None,
        ),
        api_key(
            "chutes",
            "Chutes",
            "openai-compatible",
            "https://llm.chutes.ai/v1",
            "https://chutes.ai/app/api",
            None,
        ),
        api_key(
            "cohere",
            "Cohere",
            "openai-compatible",
            "https://api.cohere.ai/compatibility/v1",
            "https://dashboard.cohere.com/api-keys",
            Some("OpenAI-compatibility endpoint."),
        ),
        api_key(
            "codebuddy-intl",
            "CodeBuddy Intl",
            "codebuddy-intl",
            "https://www.codebuddy.ai/v2",
            "https://www.codebuddy.ai/",
            Some(
                "Stream-only OpenAI-compatible API; the router injects the CodeBuddy Code system prompt.",
            ),
        ),
        api_key(
            "commandcode",
            "Command Code",
            "command-code",
            "https://api.commandcode.ai",
            "https://commandcode.ai/settings/keys",
            Some(
                "Uses the Provider API and falls back to the CLI transport when a plan has no API access (Go). Claude models only on the Anthropic surface.",
            ),
        ),
        api_key(
            "deepseek",
            "DeepSeek",
            "openai-compatible",
            "https://api.deepseek.com",
            "https://platform.deepseek.com/api_keys",
            None,
        ),
        api_key(
            "featherless",
            "Featherless",
            "openai-compatible",
            "https://api.featherless.ai/v1",
            "https://featherless.ai/account/api-keys",
            None,
        ),
        api_key(
            "fireworks",
            "Fireworks AI",
            "openai-compatible",
            "https://api.fireworks.ai/inference/v1",
            "https://fireworks.ai/account/api-keys",
            None,
        ),
        api_key(
            "glm-china",
            "GLM (China)",
            "openai-compatible",
            "https://open.bigmodel.cn/api/paas/v4",
            "https://open.bigmodel.cn/usercenter/apikeys",
            Some("Zhipu's mainland endpoint; coding-plan keys use /api/coding/paas/v4."),
        ),
        api_key(
            "glm-coding",
            "GLM Coding",
            "openai-compatible",
            "https://api.z.ai/api/coding/paas/v4",
            "https://z.ai/manage-apikey/apikey-list",
            Some("Coding-plan endpoint; quota resets daily."),
        ),
        api_key(
            "groq",
            "Groq",
            "openai-compatible",
            "https://api.groq.com/openai/v1",
            "https://console.groq.com/keys",
            None,
        ),
        api_key(
            "hyperbolic",
            "Hyperbolic",
            "openai-compatible",
            "https://api.hyperbolic.xyz/v1",
            "https://app.hyperbolic.xyz/settings",
            None,
        ),
        api_key(
            "llm7",
            "LLM7",
            "openai-compatible",
            "https://api.llm7.io/v1",
            "https://dash.llm7.io",
            Some("The anonymous token 'unused' works; a dashboard token raises limits."),
        ),
        api_key(
            "minimax",
            "Minimax Coding",
            "openai-compatible",
            "https://api.minimax.io/v1",
            "https://platform.minimaxi.com/user-center/basic-information/interface-key",
            None,
        ),
        api_key(
            "minimax-china",
            "Minimax (China)",
            "openai-compatible",
            "https://api.minimaxi.com/v1",
            "https://platform.minimaxi.com/user-center/basic-information/interface-key",
            None,
        ),
        api_key(
            "mistral",
            "Mistral",
            "openai-compatible",
            "https://api.mistral.ai/v1",
            "https://console.mistral.ai/api-keys",
            None,
        ),
        api_key(
            "moonshot",
            "Moonshot (Kimi)",
            "openai-compatible",
            "https://api.moonshot.ai/v1",
            "https://platform.moonshot.ai/console/api-keys",
            None,
        ),
        api_key(
            "morph",
            "Morph",
            "openai-compatible",
            "https://api.morphllm.com/v1",
            "https://morphllm.com",
            None,
        ),
        api_key(
            "nebius",
            "Nebius AI Studio",
            "openai-compatible",
            "https://api.studio.nebius.ai/v1",
            "https://studio.nebius.com/settings/api-keys",
            None,
        ),
        api_key(
            "openai",
            "OpenAI",
            "openai-compatible",
            "https://api.openai.com/v1",
            "https://platform.openai.com/api-keys",
            None,
        ),
        api_key(
            "opencode-go",
            "OpenCode Go",
            "openai-compatible",
            "https://opencode.ai/zen/go/v1",
            "https://opencode.ai/auth",
            Some("Subscription endpoint ($5/month)."),
        ),
        api_key(
            "perplexity",
            "Perplexity",
            "openai-compatible",
            "https://api.perplexity.ai",
            "https://www.perplexity.ai/settings/api",
            None,
        ),
        api_key(
            "siliconflow",
            "SiliconFlow",
            "openai-compatible",
            "https://api.siliconflow.com/v1",
            "https://cloud.siliconflow.com/account/ak",
            None,
        ),
        api_key(
            "tencent",
            "Tencent Hunyuan",
            "openai-compatible",
            "https://api.hunyuan.cloud.tencent.com/v1",
            "https://console.cloud.tencent.com/hunyuan/api-key",
            None,
        ),
        api_key(
            "together",
            "Together AI",
            "openai-compatible",
            "https://api.together.xyz/v1",
            "https://api.together.xyz/settings/api-keys",
            None,
        ),
        api_key(
            "tokenrouter",
            "TokenRouter",
            "openai-compatible",
            "https://api.tokenrouter.com/v1",
            "https://www.tokenrouter.com",
            Some("One key across 300+ models."),
        ),
        api_key(
            "venice",
            "Venice AI",
            "openai-compatible",
            "https://api.venice.ai/api/v1",
            "https://venice.ai/settings/api",
            None,
        ),
        api_key(
            "vercel-ai-gateway",
            "Vercel AI Gateway",
            "openai-compatible",
            "https://ai-gateway.vercel.sh/v1",
            "https://vercel.com/dashboard/~/ai-gateway",
            Some("Model ids are 'provider/model'."),
        ),
        api_key(
            "volcengine-ark",
            "Volcengine Ark",
            "openai-compatible",
            "https://ark.cn-beijing.volces.com/api/v3",
            "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
            Some("Coding-plan keys use /api/coding/v3."),
        ),
        api_key(
            "xai",
            "xAI (Grok)",
            "openai-compatible",
            "https://api.x.ai/v1",
            "https://console.x.ai",
            None,
        ),
        api_key(
            "xiaomi-mimo",
            "Xiaomi MiMo",
            "openai-compatible",
            "https://api.xiaomimimo.com/v1",
            "https://platform.xiaomimimo.com/console/api-keys",
            Some(
                "Desktop and preview models need a Xiaomi session cookie; a key cannot reach them.",
            ),
        ),
        api_key(
            "xiaomi-token-plan",
            "Xiaomi MiMo (Token Plan)",
            "openai-compatible",
            "https://token-plan-sgp.xiaomimimo.com/v1",
            "https://mimo.xiaomi.com",
            Some("Keys are region-bound: swap 'sgp' for 'cn' or 'ams' to match the key."),
        ),
        api_key(
            "zai",
            "Z.ai (GLM)",
            "openai-compatible",
            "https://api.z.ai/api/paas/v4",
            "https://z.ai/manage-apikey/apikey-list",
            Some("Coding-plan keys use a different endpoint; override the base URL."),
        ),
    ]
}

/// Hosted providers with a free tier (key or keyless).
pub(super) fn free_tier_presets() -> Vec<ProviderPreset> {
    vec![
        free_tier(
            "api-airforce",
            "API.airforce",
            "openai-compatible",
            "https://api.airforce/v1",
            "https://api.airforce",
            Some("Free tier plus pay-as-you-go on one key."),
        ),
        free_tier(
            "bazaarlink",
            "Bazaarlink",
            "openai-compatible",
            "https://bazaarlink.ai/api/v1",
            "https://bazaarlink.ai",
            Some("Free tier: 10 requests/min, 50/day; doubles after any top-up."),
        ),
        free_tier(
            "byteplus",
            "BytePlus ModelArk",
            "openai-compatible",
            "https://ark.ap-southeast.bytepluses.com/api/v3",
            "https://console.byteplus.com/ark/region:ark+ap-southeast-1/apiKey",
            Some("New accounts get free credits; coding-plan keys use /api/coding/v3."),
        ),
        free_tier(
            "cloudflare",
            "Cloudflare",
            "openai-compatible",
            "https://api.cloudflare.com/client/v4/accounts/<ACCOUNT_ID>/ai/v1",
            "https://dash.cloudflare.com/profile/api-tokens",
            Some("Replace <ACCOUNT_ID>; Workers AI has a daily free allocation."),
        ),
        free_tier(
            "gemini",
            "Google Gemini",
            "openai-compatible",
            "https://generativelanguage.googleapis.com/v1beta/openai",
            "https://aistudio.google.com/app/apikey",
            Some("Gemini's OpenAI-compatibility endpoint; free tier is rate-limited."),
        ),
        free_tier(
            "kilo-gateway",
            "Kilo Gateway",
            "openai-compatible",
            "https://api.kilo.ai/api/gateway",
            "https://kilo.ai/dashboard?tab=apiKeys",
            Some("OpenRouter-style gateway with a free tier."),
        ),
        free_tier(
            "kimchi",
            "Kimchi",
            "openai-compatible",
            "https://llm.kimchi.dev/openai/v1",
            "https://app.kimchi.dev",
            Some("$50 of credit per month, reset monthly."),
        ),
        free_tier(
            "nvidia",
            "NVIDIA NIM",
            "openai-compatible",
            "https://integrate.api.nvidia.com/v1",
            "https://build.nvidia.com/settings/api-keys",
            Some("Free for NVIDIA Developer Program members."),
        ),
        free_tier(
            "ollama-cloud",
            "Ollama Cloud",
            "openai-compatible",
            "https://ollama.com/v1",
            "https://ollama.com/settings/keys",
            Some(
                "Hosted models over Ollama's OpenAI-compatible surface; the free tier runs one cloud model at a time. Model ids look like 'gemma4:31b'.",
            ),
        ),
        free_tier(
            "openrouter",
            "OpenRouter",
            "openai-compatible",
            "https://openrouter.ai/api/v1",
            "https://openrouter.ai/settings/keys",
            Some(
                "Free models are rate-limited; optional HTTP-Referer / X-Title headers can be added below.",
            ),
        ),
        free_tier(
            "poolside",
            "Poolside",
            "openai-compatible",
            "https://inference.poolside.ai/v1",
            "https://platform.poolside.ai/api-keys",
            None,
        ),
    ]
}

/// Servers the user runs themselves.
pub(super) fn local_presets() -> Vec<ProviderPreset> {
    vec![
        local("lmstudio", "LM Studio", "http://localhost:1234/v1"),
        local("ollama", "Ollama", "http://localhost:11434/v1"),
        local("vllm", "vLLM", "http://localhost:8000/v1"),
    ]
}
